from setuptools import find_packages, setup

setup(
    name="ahc",
    version="0.1.0",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "numpy==2.2.6",
        "porepy==1.10.0",
        "scipy==1.16.1",
        "numba==0.61.2",
        "requests==2.32.5",
        "gmsh==4.14.0",
        "matplotlib==3.10.6",
        "PyQt6==6.10.2",
        "scikit-image==0.26.0",
        "seaborn==0.13.2",
        "tqdm==4.67.1",
    ],
    extras_require={
        "dev": [
            "isort==6.0.1",
            "mypy==1.17.1",
            "pytest==8.4.1",
            "ruff==0.15.8",
            "types-tqdm==4.67.3.20260205",
            "types-seaborn==0.13.2.20251221",
            "scipy-stubs==1.17.1.3",
            "types-requests==2.33.0.20260327",
            "viztracer==1.1.1",
        ],
    },
    author="Peter von Schultzendorff",
    author_email="peter.schultzendorff@uib.no",
    description="Adaptive homotopy continuation method for incompressible immiscible two-phase flow in Porous Media",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
        "Operating System :: OS Independent",
    ],
    python_requires="==3.12.11",
)
